TMZ_ShowData = {
	[57] = {
		["title"] = {
			[1] = "Tªn",
			[2] = "Phe",
			[3] = "L­u ph¸i",
			[4] = "GiÕt",
			[5] = "ChÕt",
			[6] = "TrËn nh·n",
		},
		["name"] = "Thiªn M«n trËn",
		["szFormat"] = "%-17s%-10s%-16s%-9s%-9s%-10s",
		["szMsg"] = "<enter/>  ®iÓm chiÕn trËn lµ: <color=yellow>Qu©n Tèng[365]<color>: <color=pink>[225]Qu©n Liªu<color>",
		["data"] = {
			["iBHxAnthony"] = {
				[1] = "iBHxAnthony",
				[2] = "Qu©n Tèng",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 5,
				[5] = 1,
				[6] = 3,
				[7] = 97,
				[8] = "<color=yellow>",
			},
			["iTrang"] = {
				[1] = "iTrang",
				[2] = "Qu©n Liªu",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 0,
				[6] = 0,
				[7] = 115,
				[8] = "<color=pink>",
			},
			["MarlJaack"] = {
				[1] = "MarlJaack",
				[2] = "Qu©n Tèng",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 1,
				[6] = 0,
				[7] = 169,
				[8] = "<color=yellow>",
			},
			["Ph­îngLanH­¬ng"] = {
				[1] = "Ph­îngLanH­¬ng",
				[2] = "Qu©n Tèng",
				[3] = "Tµ §éc",
				[4] = 4,
				[5] = 1,
				[6] = 3,
				[7] = 108,
				[8] = "<color=yellow>",
			},
			["Young1"] = {
				[1] = "Young1",
				[2] = "Qu©n Tèng",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 0,
				[5] = 3,
				[6] = 1,
				[7] = 38,
				[8] = "<color=yellow>",
			},
			["KhanhCuDenSTK"] = {
				[1] = "KhanhCuDenSTK",
				[2] = "Qu©n Tèng",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 8,
				[5] = 4,
				[6] = 2,
				[7] = 156,
				[8] = "<color=yellow>",
			},
			["Jx2ThamXjnhTuoi"] = {
				[1] = "Jx2ThamXjnhTuoi",
				[2] = "Qu©n Liªu",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 3,
				[5] = 2,
				[6] = 3,
				[7] = 80,
				[8] = "<color=pink>",
			},
			["ICMPiKa"] = {
				[1] = "ICMPiKa",
				[2] = "Qu©n Liªu",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 0,
				[5] = 4,
				[6] = 1,
				[7] = 113,
				[8] = "<color=pink>",
			},
			["zIzzIz"] = {
				[1] = "zIzzIz",
				[2] = "Qu©n Tèng",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 2,
				[6] = 0,
				[7] = 102,
				[8] = "<color=yellow>",
			},
			["iTPiCapsClock"] = {
				[1] = "iTPiCapsClock",
				[2] = "Qu©n Liªu",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 3,
				[5] = 4,
				[6] = 0,
				[7] = 161,
				[8] = "<color=pink>",
			},
			["Jx2iTiÓuL­uLinh"] = {
				[1] = "Jx2iTiÓuL­uLinh",
				[2] = "Qu©n Liªu",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 3,
				[6] = 0,
				[7] = 94,
				[8] = "<color=pink>",
			},
			["Th¾tBÝp"] = {
				[1] = "Th¾tBÝp",
				[2] = "Qu©n Liªu",
				[3] = "Tµ §éc",
				[4] = 0,
				[5] = 3,
				[6] = 0,
				[7] = 158,
				[8] = "<color=pink>",
			},
			["Jx2iKh¸nhNam"] = {
				[1] = "Jx2iKh¸nhNam",
				[2] = "Qu©n Tèng",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 5,
				[5] = 1,
				[6] = 0,
				[7] = 98,
				[8] = "<color=yellow>",
			},
			["xCIVxCaveBuFF"] = {
				[1] = "xCIVxCaveBuFF",
				[2] = "Qu©n Tèng",
				[3] = "Nga My phËt gia",
				[4] = 1,
				[5] = 2,
				[6] = 1,
				[7] = 52,
				[8] = "<color=yellow>",
			},
			["DóL¾cL¾c"] = {
				[1] = "DóL¾cL¾c",
				[2] = "Qu©n Tèng",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 3,
				[5] = 3,
				[6] = 0,
				[7] = 6,
				[8] = "<color=yellow>",
			},
			["XinChóChÐnR­îu"] = {
				[1] = "XinChóChÐnR­îu",
				[2] = "Qu©n Liªu",
				[3] = "ThiÕu L©m thiÒn t¨ng",
				[4] = 4,
				[5] = 3,
				[6] = 0,
				[7] = 184,
				[8] = "<color=pink>",
			},
			["BuffSongChich"] = {
				[1] = "BuffSongChich",
				[2] = "Qu©n Tèng",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 3,
				[6] = 0,
				[7] = 133,
				[8] = "<color=yellow>",
			},
			["ZzZHaS2DienZzZ"] = {
				[1] = "ZzZHaS2DienZzZ",
				[2] = "Qu©n Liªu",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 0,
				[6] = 0,
				[7] = 40,
				[8] = "<color=pink>",
			},
			["Jx2PhimHe0xxx"] = {
				[1] = "Jx2PhimHe0xxx",
				[2] = "Qu©n Tèng",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 2,
				[5] = 1,
				[6] = 0,
				[7] = 13,
				[8] = "<color=yellow>",
			},
			["iiMrKoTexx"] = {
				[1] = "iiMrKoTexx",
				[2] = "Qu©n Liªu",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 3,
				[5] = 2,
				[6] = 1,
				[7] = 93,
				[8] = "<color=pink>",
			},
			["V·iBÝp"] = {
				[1] = "V·iBÝp",
				[2] = "Qu©n Liªu",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 1,
				[6] = 0,
				[7] = 110,
				[8] = "<color=pink>",
			},
			["BÝmRung§éng"] = {
				[1] = "BÝmRung§éng",
				[2] = "Qu©n Tèng",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 2,
				[6] = 0,
				[7] = 200,
				[8] = "<color=yellow>",
			},
			["parent"] = 1,
			["NgaMyKiÕm"] = {
				[1] = "NgaMyKiÕm",
				[2] = "Qu©n Liªu",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 1,
				[6] = 0,
				[7] = 153,
				[8] = "<color=pink>",
			},
			["Jx2iBxKh¸nhNam"] = {
				[1] = "Jx2iBxKh¸nhNam",
				[2] = "Qu©n Tèng",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 0,
				[6] = 0,
				[7] = 5,
				[8] = "<color=yellow>",
			},
			["MarlJackk"] = {
				[1] = "MarlJackk",
				[2] = "Qu©n Tèng",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 7,
				[5] = 3,
				[6] = 2,
				[7] = 119,
				[8] = "<color=yellow>",
			},
			["iiMrDiana"] = {
				[1] = "iiMrDiana",
				[2] = "Qu©n Liªu",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 1,
				[6] = 0,
				[7] = 182,
				[8] = "<color=pink>",
			},
			["Jx2Huynh"] = {
				[1] = "Jx2Huynh",
				[2] = "Qu©n Liªu",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 4,
				[5] = 5,
				[6] = 2,
				[7] = 3,
				[8] = "<color=pink>",
			},
			["DonalTrump3"] = {
				[1] = "DonalTrump3",
				[2] = "Qu©n Tèng",
				[3] = "Thóy Yªn Vò N÷",
				[4] = 0,
				[5] = 1,
				[6] = 0,
				[7] = 31,
				[8] = "<color=yellow>",
			},
			["Jx2Nyn"] = {
				[1] = "Jx2Nyn",
				[2] = "Qu©n Liªu",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 1,
				[6] = 0,
				[7] = 51,
				[8] = "<color=pink>",
			},
			["iC«ngLùc"] = {
				[1] = "iC«ngLùc",
				[2] = "Qu©n Liªu",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 6,
				[5] = 1,
				[6] = 1,
				[7] = 162,
				[8] = "<color=pink>",
			},
		},
	},
	[58] = {
		["title"] = {
			[1] = "Tªn",
			[2] = "Phe",
			[3] = "L­u ph¸i",
			[4] = "GiÕt",
			[5] = "ChÕt",
			[6] = "TrËn nh·n",
		},
		["name"] = "Thiªn M«n trËn",
		["szFormat"] = "%-17s%-10s%-16s%-9s%-9s%-10s",
		["szMsg"] = "Tû lÖ chiÕm trËn: <color=yellow>Qu©n Tèng[0]<color>: <color=pink>[0]Qu©n Liªu<color>",
		["data"] = {
			["ZToKuDaZ"] = {
				[1] = "ZToKuDaZ",
				[2] = "Qu©n Liªu",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 0,
				[5] = 0,
				[6] = 0,
				[7] = 12,
				[8] = "<color=pink>",
			},
			["iMyLife"] = {
				[1] = "iMyLife",
				[2] = "Qu©n Tèng",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 0,
				[6] = 0,
				[7] = 165,
				[8] = "<color=yellow>",
			},
			["zBxToKuDaz"] = {
				[1] = "zBxToKuDaz",
				[2] = "Qu©n Liªu",
				[3] = "Nga My phËt gia",
				[4] = 0,
				[5] = 0,
				[6] = 0,
				[7] = 86,
				[8] = "<color=pink>",
			},
			["iMyDream"] = {
				[1] = "iMyDream",
				[2] = "Qu©n Tèng",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 0,
				[5] = 0,
				[6] = 0,
				[7] = 50,
				[8] = "<color=yellow>",
			},
			["Hantermen"] = {
				[1] = "Hantermen",
				[2] = "Qu©n Tèng",
				[3] = "D­¬ng M«n Cung Kþ",
				[4] = 0,
				[5] = 0,
				[6] = 0,
				[7] = 55,
				[8] = "<color=yellow>",
			},
			["parent"] = 2,
		},
	},
	["title"] = {
		[1] = "Tªn",
		[2] = "Phe",
		[3] = "L­u ph¸i",
		[4] = "GiÕt",
		[5] = "ChÕt",
		[6] = "TrËn nh·n",
	},
	["name"] = "Thiªn M«n trËn",
	["szFormat"] = "%-17s%-10s%-16s%-9s%-9s%-10s",
	["CurN"] = 349,
}
